# Generated by Django 4.2 on 2023-05-01 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mobileapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMobileApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screenshot", models.ImageField(upload_to="screenshot/")),
                (
                    "mobile_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobileapp.mobileapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
