# Generated by Django 4.2 on 2023-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileapp", "0002_usermobileapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileapp",
            name="logo",
            field=models.ImageField(null=True, upload_to="app-logo/"),
        ),
    ]
